project_id = "akchmpmzcupzjaeewdui"

[functions.manage-domain]
verify_jwt = true

[functions.create-booking]
verify_jwt = true

[functions.sync]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.reconcile-transactions]
verify_jwt = true

[functions.auto-sync-reconciliation]
verify_jwt = true

