project_id = "akchmpmzcupzjaeewdui"

[functions.purchase-sms-bundle]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.reset-password]
verify_jwt = true

[functions.invite-staff]
verify_jwt = true

[functions.manage-staff]
verify_jwt = true

[functions.apply-wallet-credit]
verify_jwt = true

[functions.auto-sync-reconciliation]
verify_jwt = true

[functions.charge-to-organization]
verify_jwt = true

[functions.complete-checkout]
verify_jwt = true

[functions.create-booking]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.force-checkout]
verify_jwt = true

[functions.manage-domain]
verify_jwt = true

[functions.recalculate-financials]
verify_jwt = true

[functions.reconcile-transactions]
verify_jwt = true

[functions.sync]
verify_jwt = true

[functions.sync-room-bookings]
verify_jwt = true

[functions.validate-booking]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

