project_id = "akchmpmzcupzjaeewdui"

[functions.manage-domain]
verify_jwt = true

[functions.create-booking]
verify_jwt = true

[functions.sync]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true
